services:


  frontend:
    image: alejoide/my-links-web:dev
    build:
      context: ../src
      dockerfile: ./Dockerfile
    container_name: my-links-frontend
    env_file:
      - ./config/.frontend.env
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default


volumes:
  static:
