services:

  frontend:
    image: alejoide/my-links-web:latest
    container_name: my-links-frontend
    restart: unless-stopped
    env_file:
      - ./config/.frontend.env
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
      - nginx-proxy

volumes:
  static:

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true
